# Generated by Django 5.1.3 on 2024-11-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='Collection',
        ),
    ]
