# Generated by Django 5.1.3 on 2024-11-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_product_order_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Collection',
            new_name='collection',
        ),
    ]
